### ISSUE TITLE
Bluetooth earbuds / headsets sound is having interference with WiFi

### ISSUE THREAD

**Issue by raavanaX** [AnterCreeper/linux-on-elitepad1000g2#1]
Bluetooth earbuds / headset sound is having interference with WiFi network(card). 
Likewise data transfer is heavily limited when a Bluetooth device is connected.

**Comment by raavanaX** [comment]
Elitepad 1000g2 uses Broadcom BCM43241 Bluetooth 4.0 at 2.4ghz. So connecting your wifi card to a 5ghz band of your router resolves the issue.

**Comment by AnterCreeper** [comment]
the bluetooth's audio is transfered via I2S and data via UART(a limited bus) according to the schematic. And wifi is via SDIO. So the bluetooth should not be used in heavy scenario。
