### ISSUE TITLE
Sound on Elitepad 1000G2

### ISSUE THREAD

**Issue by DansDesigns** [AnterCreeper/linux-on-elitepad1000g2#2]
Hey thanks for putting all this together!
I am trying to get sound working on my fathers Elitepad 1000 G2 running ZorinOS 16 Core..
Everything works except on-board sound, headphone jack and microphones..
How does one install these changes to enable sound output?
Thank you again

**Comment by AnterCreeper** [comment]
https://github.com/torvalds/linux/commit/9ba00856686ade106afee2884b5e8ac1e09d137a
https://github.com/torvalds/linux/commit/0a61bcbba8737fe6d43dc34070ffa84a2f12e990

kernel after these commits will be ok.
for versions before, you need to make a dkms version of this driver.
